// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseFruitCard: typeof import('./components/ui/BaseFruitCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskDetails: typeof import('./components/TaskDetails.vue')['default']
    TheHeader: typeof import('./components/layouts/TheHeader.vue')['default']
  }
}
