export default [
  {
    family: "Musaceae",
    genus: "Musa",
    id: 1,
    img: "https://cdn.shopify.com/s/files/1/0268/2817/7615/products/BananasNEW_43d2f6b9-826e-4350-9b8d-ee84159d3f5c.jpg?v=1642449327",
    isCompared: true,
    isFavorited: false,
    name: "Banana",
    nutritions: {
      calories: 96,
      carbohydrates: 22,
      fat: 0.2,
      protein: 1,
      sugar: 17.2,
    },
    order: "Zingiberales",
  },
  {
    family: "Rutaceae",
    genus: "Citrus",
    id: 2,
    img: "https://thumbs.dreamstime.com/b/orange-fruit-isolated-white-background-leaf-34443518.jpg",
    isCompared: true,
    isFavorited: false,
    name: "Orange",
    nutritions: {
      calories: 43,
      carbohydrates: 8.3,
      fat: 0.2,
      protein: 1,
      sugar: 8.2,
    },
    order: "Sapindales",
  },
  {
    family: "Rosaceae",
    genus: "Fragaria",
    id: 3,
    img: "https://tastyfoodeg.com/wp-content/uploads/2018/12/p11.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Strawberry",
    nutritions: {
      calories: 29,
      carbohydrates: 5.5,
      fat: 0.4,
      protein: 0.8,
      sugar: 5.4,
    },
    order: "Rosales",
  },
  {
    family: "Rosaceae",
    genus: "Pyrus",
    id: 4,
    img: "https://4.imimg.com/data4/SI/GW/MY-15929133/fresh-papaya-500x500.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Pear",
    nutritions: {
      calories: 57,
      carbohydrates: 15,
      fat: 0.1,
      protein: 0.4,
      sugar: 10,
    },
    order: "Rosales",
  },
  {
    family: "Solanaceae",
    genus: "Solanum",
    id: 5,
    img: "https://img3.zakaz.ua/src.1605017085.ad72436478c_2020-11-10_Victor/src.1605017085.SNCPSG10.obj.0.1.jpg.oe.jpg.pf.jpg.350nowm.jpg.350x.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Tomato",
    nutritions: {
      calories: 74,
      carbohydrates: 3.9,
      fat: 0.2,
      protein: 0.9,
      sugar: 2.6,
    },
    order: "Solanales",
  },
  {
    family: "Rosaceae",
    genus: "Malus",
    id: 6,
    img: "https://cooker.net.ua/upload/iblock/8df/yabluko_chervone_1029.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Apple",
    nutritions: {
      calories: 52,
      carbohydrates: 11.4,
      fat: 0.4,
      protein: 0.3,
      sugar: 10.3,
    },
    order: "Rosales",
  },
  {
    family: "Rosaceae",
    genus: "Prunus",
    id: 9,
    img: "https://sc04.alicdn.com/kf/UTB8B4X1ktnJXKJkSaiyq6AhwXXaD.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Cherry",
    nutritions: {
      calories: 50,
      carbohydrates: 12,
      fat: 0.3,
      protein: 1,
      sugar: 8,
    },
    order: "Rosales",
  },
  {
    family: "Bromeliaceae",
    genus: "Ananas",
    id: 10,
    img: "https://nisargafoods.com/image/cache/catalog/Fruits/pineapple%20size-800x800.png",
    isCompared: false,
    isFavorited: false,
    name: "Pineapple",
    nutritions: {
      calories: 50,
      carbohydrates: 13.12,
      fat: 0.12,
      protein: 0.54,
      sugar: 9.85,
    },
    order: "Poales",
  },
  {
    family: "Rosaceae",
    genus: "Rubus",
    id: 23,
    img: "https://t0.gstatic.com/images?q=tbn:ANd9GcRn0wU2x4X22KIng4i9ztYnLJax37a_UTHU9CX6ROqxILPau6ka",
    isCompared: false,
    isFavorited: false,
    name: "Raspberry",
    nutritions: {
      calories: 53,
      carbohydrates: 12,
      fat: 0.7,
      protein: 1.2,
      sugar: 4.4,
    },
    order: "Rosales",
  },
  {
    family: "Cucurbitaceae",
    genus: "Citrullus",
    id: 25,
    img: "https://www.natureinbottle.com/upload/product_ecom/Watermelon-Hydrosol-Citrullus-vulgaris-Hydrolat-ProductPic.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Watermelon",
    nutritions: {
      calories: 30,
      carbohydrates: 8,
      fat: 0.2,
      protein: 0.6,
      sugar: 6,
    },
    order: "Cucurbitales",
  },
  {
    family: "Rutaceae",
    genus: "Citrus",
    id: 26,
    img: "https://www.ortis.com/media/plant/citrusimonum-risso.png",
    isCompared: false,
    isFavorited: false,
    name: "Lemon",
    nutritions: {
      calories: 29,
      carbohydrates: 9,
      fat: 0.3,
      protein: 1.1,
      sugar: 2.5,
    },
    order: "Sapindales",
  },
  {
    family: "Anacardiaceae",
    genus: "Mangifera",
    id: 27,
    img: "https://www.fayadsfruits.com/131-large_default/mango-ready-.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Mango",
    nutritions: {
      calories: 60,
      carbohydrates: 15,
      fat: 0.38,
      protein: 0.82,
      sugar: 13.7,
    },
    order: "Sapindales",
  },
  {
    family: "Rosaceae",
    genus: "Fragaria",
    id: 33,
    img: "https://www.greenearthorganics.ie/image/cache/data/blueberries-web-800x800.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Blueberry",
    nutritions: {
      calories: 29,
      carbohydrates: 5.5,
      fat: 0.4,
      protein: 0,
      sugar: 5.4,
    },
    order: "Rosales",
  },
  {
    family: "Rosaceae",
    genus: "Prunus",
    id: 35,
    img: "https://cdn.shopify.com/s/files/1/1254/5779/files/Peachcot-apricot.jpg?v=1619548478",
    isCompared: false,
    isFavorited: false,
    name: "Apricot",
    nutritions: {
      calories: 15,
      carbohydrates: 3.9,
      fat: 0.1,
      protein: 0.5,
      sugar: 3.2,
    },
    order: "Rosales",
  },
  {
    family: "Myrtaceae",
    genus: "Psidium",
    id: 37,
    img: "https://cdn.shopify.com/s/files/1/0258/4307/3103/products/asset_19_800x.jpg?v=1594383262",
    isCompared: false,
    isFavorited: false,
    name: "Guava",
    nutritions: {
      calories: 68,
      carbohydrates: 14,
      fat: 1,
      protein: 2.6,
      sugar: 9,
    },
    order: "Myrtales",
  },
  {
    family: "Cucurbitaceae",
    genus: "Cucumis",
    id: 41,
    img: "https://www.blifesrl.it/wp-content/uploads/2021/03/melon-de-galia-ecologico-1-kg-800x800-1.jpeg",
    isCompared: false,
    isFavorited: false,
    name: "Melon",
    nutritions: {
      calories: 34,
      carbohydrates: 8,
      fat: 0,
      protein: 0,
      sugar: 8,
    },
    order: "Cucurbitaceae",
  },
  {
    family: "Caricaceae",
    genus: "Carica",
    id: 42,
    img: "https://kiakesh.com/image/cache/catalog/800/Papaya-800x800.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Papaya",
    nutritions: {
      calories: 43,
      carbohydrates: 11,
      fat: 0.4,
      protein: 0,
      sugar: 1,
    },
    order: "Caricacea",
  },
  {
    family: "Rutaceae",
    genus: "Citrus",
    id: 44,
    img: "https://www.homestratosphere.com/wp-content/uploads/2019/01/1-18-1.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Lime",
    nutritions: {
      calories: 25,
      carbohydrates: 8.4,
      fat: 0.1,
      protein: 0.3,
      sugar: 1.7,
    },
    order: "Sapindales",
  },
  {
    family: "Ebenaceae",
    genus: "Diospyros",
    id: 52,
    img: "https://uploads-ssl.webflow.com/6022f72424aa6065f647ee59/63dab56e56f75fd1ae41db94_Presimmon%20fresh.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Persimmon",
    nutritions: {
      calories: 81,
      carbohydrates: 18,
      fat: 0,
      protein: 0,
      sugar: 18,
    },
    order: "Rosales",
  },
  {
    family: "Malvaceae",
    genus: "Durio",
    id: 60,
    img: "https://cdn.shopify.com/s/files/1/0663/6951/9849/products/1_98d79627-012e-4244-86f9-99324b3d85cd.jpg?v=1664938999",
    isCompared: false,
    isFavorited: false,
    name: "Durian",
    nutritions: {
      calories: 147,
      carbohydrates: 27.1,
      fat: 5.3,
      protein: 1.5,
      sugar: 6.75,
    },
    order: "Malvales",
  },
  {
    family: "Rosaceae",
    genus: "Rubus",
    id: 64,
    img: "https://frenchgourmand.eu/3966-large_default/blackberry-125g-holland.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Blackberry",
    nutritions: {
      calories: 40,
      carbohydrates: 9,
      fat: 0.4,
      protein: 1.3,
      sugar: 4.5,
    },
    order: "Rosales",
  },
  {
    family: "Ericaceae",
    genus: "Vaccinium",
    id: 65,
    img: "https://www.seeds-gallery.eu/7697-large_default/lingonberry-or-cowberry-seed.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Lingonberry",
    nutritions: {
      calories: 50,
      carbohydrates: 11.3,
      fat: 0.34,
      protein: 0.75,
      sugar: 5.74,
    },
    order: "Ericales",
  },
  {
    family: "Actinidiaceae",
    genus: "Apteryx",
    id: 66,
    img: "https://www.exotic-seeds.store/2851-large_default/giant-kiwifruit-seeds.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Kiwi",
    nutritions: {
      calories: 61,
      carbohydrates: 15,
      fat: 0.5,
      protein: 1.1,
      sugar: 9,
    },
    order: "Struthioniformes",
  },
  {
    family: "Sapindaceae",
    genus: "Litchi",
    id: 67,
    img: "https://fosacha.com/upload/product/thumb_800x0/-1646189575.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Lychee",
    nutritions: {
      calories: 66,
      carbohydrates: 17,
      fat: 0.44,
      protein: 0.8,
      sugar: 15,
    },
    order: "Sapindales",
  },
  {
    family: "Moraceae",
    genus: "Ficus",
    id: 68,
    img: "https://zonefresh.com.au/wp-content/uploads/FIGS-EACH.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Fig",
    nutritions: {
      calories: 74,
      carbohydrates: 19,
      fat: 0.3,
      protein: 0.8,
      sugar: 16,
    },
    order: "Rosales",
  },
  {
    family: "Grossulariaceae",
    genus: "Ribes",
    id: 69,
    img: "https://www.fayadsfruits.com/118-large_default/gooseberry-125-g.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Gooseberry",
    nutritions: {
      calories: 44,
      carbohydrates: 10,
      fat: 0.6,
      protein: 0.9,
      sugar: 0,
    },
    order: "Saxifragales",
  },
  {
    family: "Passifloraceae",
    genus: "Passiflora",
    id: 70,
    img: "https://www.natureinbottle.com/upload/product_ecom/Passionfruit-Seed-Maracuja-Oil.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Passionfruit",
    nutritions: {
      calories: 97,
      carbohydrates: 22.4,
      fat: 0.7,
      protein: 2.2,
      sugar: 11.2,
    },
    order: "Malpighiales",
  },
  {
    family: "Rosaceae",
    genus: "Prunus",
    id: 71,
    img: "https://www.natureinbottle.com/upload/product_ecom/Plum-Kernel-Oil.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Plum",
    nutritions: {
      calories: 46,
      carbohydrates: 11.4,
      fat: 0.28,
      protein: 0.7,
      sugar: 9.92,
    },
    order: "Rosales",
  },
  {
    family: "Rosaceae",
    genus: "Malus",
    id: 72,
    img: "https://www.fruitzu.com/image/cache/catalog/product/green%20apple-800x800.jpg",
    isCompared: false,
    isFavorited: false,
    name: "GreenApple",
    nutritions: {
      calories: 21,
      carbohydrates: 3.1,
      fat: 0.1,
      protein: 0.4,
      sugar: 6.4,
    },
    order: "Rosales",
  },
  {
    family: "Myrtaceae",
    genus: "Sellowiana",
    id: 76,
    img: "https://fruland.co/Tienda/26-thickbox_default/pulpa-de-feijoa.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Feijoa",
    nutritions: {
      calories: 44,
      carbohydrates: 8,
      fat: 0.4,
      protein: 0.6,
      sugar: 3,
    },
    order: "Myrtoideae",
  },
  {
    family: "Rutaceae",
    genus: "Citrus",
    id: 77,
    img: "https://images.prom.ua/1904255822_w640_h640_tangerine-juice-concentrate.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Tangerine",
    nutritions: {
      calories: 45,
      carbohydrates: 8.3,
      fat: 0.4,
      protein: 0,
      sugar: 9.1,
    },
    order: "Sapindales",
  },
  {
    family: "Lythraceae",
    genus: "Punica",
    id: 79,
    img: "https://cdn.shopify.com/s/files/1/1488/2350/products/spanish_sweet.jpg?v=1513872431",
    isCompared: false,
    isFavorited: false,
    name: "Pomegranate",
    nutritions: {
      calories: 83,
      carbohydrates: 18.7,
      fat: 1.2,
      protein: 1.7,
      sugar: 13.7,
    },
    order: "Myrtales",
  },
  {
    family: "Cactaceae",
    genus: "Selenicereus",
    id: 80,
    img: "https://cdn.shopify.com/s/files/1/0358/7879/7448/products/dragon_fruit_800x.png?v=1620848158",
    isCompared: false,
    isFavorited: false,
    name: "Dragonfruit",
    nutritions: {
      calories: 60,
      carbohydrates: 9,
      fat: 1.5,
      protein: 9,
      sugar: 8,
    },
    order: "Caryophyllales",
  },
  {
    family: "Vitaceae",
    genus: "Vitis",
    id: 81,
    img: "https://cdn.shopify.com/s/files/1/0270/8127/7520/products/8_50362fc9-5f01-41a4-811d-2732b7e1fed8_1200x.png?v=1621939087",
    isCompared: false,
    isFavorited: false,
    name: "Grape",
    nutritions: {
      calories: 69,
      carbohydrates: 18.1,
      fat: 0.16,
      protein: 0.72,
      sugar: 16,
    },
    order: "Vitales",
  },
  {
    family: "Moraceae",
    genus: "Morus",
    id: 82,
    img: "https://www.seeds-gallery.eu/5860-large_default/black-mulberry-seeds.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Morus",
    nutritions: {
      calories: 43,
      carbohydrates: 9.8,
      fat: 0.39,
      protein: 1.44,
      sugar: 8.1,
    },
    order: "Rosales",
  },
  {
    family: "Lauraceae",
    genus: "Persea",
    id: 84,
    img: "https://www.dole.com/-/media/project/dole/produce-images/fruit/avocados_cut_web.png",
    isCompared: false,
    isFavorited: false,
    name: "Avocado",
    nutritions: {
      calories: 160,
      carbohydrates: 8.53,
      fat: 14.66,
      protein: 2,
      sugar: 0.66,
    },
    order: "Laurales",
  },
  {
    family: "Rosaceae",
    genus: "Prunus",
    id: 86,
    img: "https://www.meyco.com.tr/wp-content/uploads/2022/04/seftali-photo-800x800.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Peach",
    nutritions: {
      calories: 39,
      carbohydrates: 9.5,
      fat: 0.25,
      protein: 0.9,
      sugar: 8.4,
    },
    order: "Rosales",
  },
  {
    family: "Ericaceae",
    genus: "Vaccinium",
    id: 87,
    img: "https://www.nationalgardens.in/177-large_default/cranberry-fruit-seeds.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Cranberry",
    nutritions: {
      calories: 46,
      carbohydrates: 12.2,
      fat: 0.1,
      protein: 0.4,
      sugar: 4,
    },
    order: "Ericales",
  },
];