export default [
  {
    family: "Musaceae",
    genus: "Musa",
    id: 1,
    img: "@/assets/fruits/banana.jpg",
    isCompared: true,
    isFavorited: false,
    name: "Banana",
    nutritions: {
      calories: 96,
      carbohydrates: 22,
      fat: 0.2,
      protein: 1,
      sugar: 17.2,
    },
    order: "Zingiberales",
  },
  {
    family: "Rutaceae",
    genus: "Citrus",
    id: 2,
    img: "@/assets/fruits/orange.jpg",
    isCompared: true,
    isFavorited: false,
    name: "Orange",
    nutritions: {
      calories: 43,
      carbohydrates: 8.3,
      fat: 0.2,
      protein: 1,
      sugar: 8.2,
    },
    order: "Sapindales",
  },
  {
    family: "Rosaceae",
    genus: "Fragaria",
    id: 3,
    img: "@/assets/fruits/strawberry.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Strawberry",
    nutritions: {
      calories: 29,
      carbohydrates: 5.5,
      fat: 0.4,
      protein: 0.8,
      sugar: 5.4,
    },
    order: "Rosales",
  },
  {
    family: "Rosaceae",
    genus: "Pyrus",
    id: 4,
    img: "@/assets/fruits/pear.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Pear",
    nutritions: {
      calories: 57,
      carbohydrates: 15,
      fat: 0.1,
      protein: 0.4,
      sugar: 10,
    },
    order: "Rosales",
  },
  {
    family: "Solanaceae",
    genus: "Solanum",
    id: 5,
    img: "@/assets/fruits/tomato.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Tomato",
    nutritions: {
      calories: 74,
      carbohydrates: 3.9,
      fat: 0.2,
      protein: 0.9,
      sugar: 2.6,
    },
    order: "Solanales",
  },
  {
    family: "Rosaceae",
    genus: "Malus",
    id: 6,
    img: "@/assets/fruits/apple.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Apple",
    nutritions: {
      calories: 52,
      carbohydrates: 11.4,
      fat: 0.4,
      protein: 0.3,
      sugar: 10.3,
    },
    order: "Rosales",
  },
  {
    family: "Rosaceae",
    genus: "Prunus",
    id: 9,
    img: "@/assets/fruits/cherry.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Cherry",
    nutritions: {
      calories: 50,
      carbohydrates: 12,
      fat: 0.3,
      protein: 1,
      sugar: 8,
    },
    order: "Rosales",
  },
  {
    family: "Bromeliaceae",
    genus: "Ananas",
    id: 10,
    img: "@/assets/fruits/pineapple.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Pineapple",
    nutritions: {
      calories: 50,
      carbohydrates: 13.12,
      fat: 0.12,
      protein: 0.54,
      sugar: 9.85,
    },
    order: "Poales",
  },
  {
    family: "Rosaceae",
    genus: "Rubus",
    id: 23,
    img: "@/assets/fruits/raspberry.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Raspberry",
    nutritions: {
      calories: 53,
      carbohydrates: 12,
      fat: 0.7,
      protein: 1.2,
      sugar: 4.4,
    },
    order: "Rosales",
  },
  {
    family: "Cucurbitaceae",
    genus: "Citrullus",
    id: 25,
    img: "@/assets/fruits/watermelon.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Watermelon",
    nutritions: {
      calories: 30,
      carbohydrates: 8,
      fat: 0.2,
      protein: 0.6,
      sugar: 6,
    },
    order: "Cucurbitales",
  },
  {
    family: "Rutaceae",
    genus: "Citrus",
    id: 26,
    img: "@/assets/fruits/lemon.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Lemon",
    nutritions: {
      calories: 29,
      carbohydrates: 9,
      fat: 0.3,
      protein: 1.1,
      sugar: 2.5,
    },
    order: "Sapindales",
  },
  {
    family: "Anacardiaceae",
    genus: "Mangifera",
    id: 27,
    img: "@/assets/fruits/mango.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Mango",
    nutritions: {
      calories: 60,
      carbohydrates: 15,
      fat: 0.38,
      protein: 0.82,
      sugar: 13.7,
    },
    order: "Sapindales",
  },
  {
    family: "Rosaceae",
    genus: "Fragaria",
    id: 33,
    img: "@/assets/fruits/blueberry.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Blueberry",
    nutritions: {
      calories: 29,
      carbohydrates: 5.5,
      fat: 0.4,
      protein: 0,
      sugar: 5.4,
    },
    order: "Rosales",
  },
  {
    family: "Rosaceae",
    genus: "Prunus",
    id: 35,
    img: "@/assets/fruits/apricot.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Apricot",
    nutritions: {
      calories: 15,
      carbohydrates: 3.9,
      fat: 0.1,
      protein: 0.5,
      sugar: 3.2,
    },
    order: "Rosales",
  },
  {
    family: "Myrtaceae",
    genus: "Psidium",
    id: 37,
    img: "@/assets/fruits/guava.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Guava",
    nutritions: {
      calories: 68,
      carbohydrates: 14,
      fat: 1,
      protein: 2.6,
      sugar: 9,
    },
    order: "Myrtales",
  },
  {
    family: "Cucurbitaceae",
    genus: "Cucumis",
    id: 41,
    img: "@/assets/fruits/melon.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Melon",
    nutritions: {
      calories: 34,
      carbohydrates: 8,
      fat: 0,
      protein: 0,
      sugar: 8,
    },
    order: "Cucurbitaceae",
  },
  {
    family: "Caricaceae",
    genus: "Carica",
    id: 42,
    img: "@/assets/fruits/papaya.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Papaya",
    nutritions: {
      calories: 43,
      carbohydrates: 11,
      fat: 0.4,
      protein: 0,
      sugar: 1,
    },
    order: "Caricacea",
  },
  {
    family: "Rutaceae",
    genus: "Citrus",
    id: 44,
    img: "@/assets/fruits/lime.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Lime",
    nutritions: {
      calories: 25,
      carbohydrates: 8.4,
      fat: 0.1,
      protein: 0.3,
      sugar: 1.7,
    },
    order: "Sapindales",
  },
  {
    family: "Ebenaceae",
    genus: "Diospyros",
    id: 52,
    img: "@/assets/fruits/persimmon.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Persimmon",
    nutritions: {
      calories: 81,
      carbohydrates: 18,
      fat: 0,
      protein: 0,
      sugar: 18,
    },
    order: "Rosales",
  },
  {
    family: "Malvaceae",
    genus: "Durio",
    id: 60,
    img: "@/assets/fruits/durian.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Durian",
    nutritions: {
      calories: 147,
      carbohydrates: 27.1,
      fat: 5.3,
      protein: 1.5,
      sugar: 6.75,
    },
    order: "Malvales",
  },
  {
    family: "Rosaceae",
    genus: "Rubus",
    id: 64,
    img: "@/assets/fruits/blackberry.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Blackberry",
    nutritions: {
      calories: 40,
      carbohydrates: 9,
      fat: 0.4,
      protein: 1.3,
      sugar: 4.5,
    },
    order: "Rosales",
  },
  {
    family: "Ericaceae",
    genus: "Vaccinium",
    id: 65,
    img: "@/assets/fruits/lingonberry.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Lingonberry",
    nutritions: {
      calories: 50,
      carbohydrates: 11.3,
      fat: 0.34,
      protein: 0.75,
      sugar: 5.74,
    },
    order: "Ericales",
  },
  {
    family: "Actinidiaceae",
    genus: "Apteryx",
    id: 66,
    img: "@/assets/fruits/kiwi.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Kiwi",
    nutritions: {
      calories: 61,
      carbohydrates: 15,
      fat: 0.5,
      protein: 1.1,
      sugar: 9,
    },
    order: "Struthioniformes",
  },
  {
    family: "Sapindaceae",
    genus: "Litchi",
    id: 67,
    img: "@/assets/fruits/lychee.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Lychee",
    nutritions: {
      calories: 66,
      carbohydrates: 17,
      fat: 0.44,
      protein: 0.8,
      sugar: 15,
    },
    order: "Sapindales",
  },
  {
    family: "Moraceae",
    genus: "Ficus",
    id: 68,
    img: "@/assets/fruits/fig.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Fig",
    nutritions: {
      calories: 74,
      carbohydrates: 19,
      fat: 0.3,
      protein: 0.8,
      sugar: 16,
    },
    order: "Rosales",
  },
  {
    family: "Grossulariaceae",
    genus: "Ribes",
    id: 69,
    img: "@/assets/fruits/gooseberry.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Gooseberry",
    nutritions: {
      calories: 44,
      carbohydrates: 10,
      fat: 0.6,
      protein: 0.9,
      sugar: 0,
    },
    order: "Saxifragales",
  },
  {
    family: "Passifloraceae",
    genus: "Passiflora",
    id: 70,
    img: "@/assets/fruits/passionfruit.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Passionfruit",
    nutritions: {
      calories: 97,
      carbohydrates: 22.4,
      fat: 0.7,
      protein: 2.2,
      sugar: 11.2,
    },
    order: "Malpighiales",
  },
  {
    family: "Rosaceae",
    genus: "Prunus",
    id: 71,
    img: "@/assets/fruits/plum.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Plum",
    nutritions: {
      calories: 46,
      carbohydrates: 11.4,
      fat: 0.28,
      protein: 0.7,
      sugar: 9.92,
    },
    order: "Rosales",
  },
  {
    family: "Rosaceae",
    genus: "Malus",
    id: 72,
    img: "@/assets/fruits/green-apple.jpg",
    isCompared: false,
    isFavorited: false,
    name: "GreenApple",
    nutritions: {
      calories: 21,
      carbohydrates: 3.1,
      fat: 0.1,
      protein: 0.4,
      sugar: 6.4,
    },
    order: "Rosales",
  },
  {
    family: "Myrtaceae",
    genus: "Sellowiana",
    id: 76,
    img: "@/assets/fruits/feijoa.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Feijoa",
    nutritions: {
      calories: 44,
      carbohydrates: 8,
      fat: 0.4,
      protein: 0.6,
      sugar: 3,
    },
    order: "Myrtoideae",
  },
  {
    family: "Rutaceae",
    genus: "Citrus",
    id: 77,
    img: "@/assets/fruits/tangerine.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Tangerine",
    nutritions: {
      calories: 45,
      carbohydrates: 8.3,
      fat: 0.4,
      protein: 0,
      sugar: 9.1,
    },
    order: "Sapindales",
  },
  {
    family: "Lythraceae",
    genus: "Punica",
    id: 79,
    img: "@/assets/fruits/pomegranate.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Pomegranate",
    nutritions: {
      calories: 83,
      carbohydrates: 18.7,
      fat: 1.2,
      protein: 1.7,
      sugar: 13.7,
    },
    order: "Myrtales",
  },
  {
    family: "Cactaceae",
    genus: "Selenicereus",
    id: 80,
    img: "@/assets/fruits/dragonfruit.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Dragonfruit",
    nutritions: {
      calories: 60,
      carbohydrates: 9,
      fat: 1.5,
      protein: 9,
      sugar: 8,
    },
    order: "Caryophyllales",
  },
  {
    family: "Vitaceae",
    genus: "Vitis",
    id: 81,
    img: "@/assets/fruits/grape.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Grape",
    nutritions: {
      calories: 69,
      carbohydrates: 18.1,
      fat: 0.16,
      protein: 0.72,
      sugar: 16,
    },
    order: "Vitales",
  },
  {
    family: "Moraceae",
    genus: "Morus",
    id: 82,
    img: "@/assets/fruits/morus.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Morus",
    nutritions: {
      calories: 43,
      carbohydrates: 9.8,
      fat: 0.39,
      protein: 1.44,
      sugar: 8.1,
    },
    order: "Rosales",
  },
  {
    family: "Lauraceae",
    genus: "Persea",
    id: 84,
    img: "@/assets/fruits/avocado.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Avocado",
    nutritions: {
      calories: 160,
      carbohydrates: 8.53,
      fat: 14.66,
      protein: 2,
      sugar: 0.66,
    },
    order: "Laurales",
  },
  {
    family: "Rosaceae",
    genus: "Prunus",
    id: 86,
    img: "@/assets/fruits/peach.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Peach",
    nutritions: {
      calories: 39,
      carbohydrates: 9.5,
      fat: 0.25,
      protein: 0.9,
      sugar: 8.4,
    },
    order: "Rosales",
  },
  {
    family: "Ericaceae",
    genus: "Vaccinium",
    id: 87,
    img: "@/assets/fruits/cranberry.jpg",
    isCompared: false,
    isFavorited: false,
    name: "Cranberry",
    nutritions: {
      calories: 46,
      carbohydrates: 12.2,
      fat: 0.1,
      protein: 0.4,
      sugar: 4,
    },
    order: "Ericales",
  },
];