// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseCompareCard: typeof import('./components/ui/BaseCompareCard.vue')['default']
    BaseFruitCard: typeof import('./components/ui/BaseFruitCard.vue')['default']
    BaseFruitLength: typeof import('./components/ui/BaseFruitLength.vue')['default']
    BaseNotFoundFruit: typeof import('./components/ui/BaseNotFoundFruit.vue')['default']
    CompareIcon: typeof import('./components/compare/CompareIcon.vue')['default']
    CompareLength: typeof import('./components/compare/CompareLength.vue')['default']
    CompareTable: typeof import('./components/compare/CompareTable.vue')['default']
    CompareTableHeaders: typeof import('./components/compare/CompareTableHeaders.vue')['default']
    CompareTableList: typeof import('./components/compare/CompareTableList.vue')['default']
    FavoriteIcon: typeof import('./components/favorite/FavoriteIcon.vue')['default']
    FilterList: typeof import('./components/filter/FilterList.vue')['default']
    FruitLength: typeof import('./components/ui/FruitLength.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./components/search/SearchBar.vue')['default']
    TheContainerHeader: typeof import('./components/layouts/TheContainerHeader.vue')['default']
    TheFilter: typeof import('./components/layouts/TheFilter.vue')['default']
    TheHeader: typeof import('./components/layouts/TheHeader.vue')['default']
  }
}
